name: 'Remove Issue Labels'
description: 'Remove label from issue'
inputs:
  github_token:
    description: A GitHub token.
    required: true
  labels:
    description: The labels' name to be removed. Must be separated with line breaks if there're multiple labels.
    required: true
runs:
  using: 'node12'
  main: 'index.js'